### ISSUE TITLE
No module named greenmine.config

### ISSUE THREAD

**Issue by dArignac** [kaleidos-ventures/taiga-front-old#1]
Hi there,

I'm trying to run the frontend for greenmine, but it cannot find a specific module "greenmine.config" when I open localhost:9001 in the browser:

```
Uncaught Error: No module: greenmine.config
```

I guess this is just a config connecting the frontend to the backend, but as I do not really know grunt, I don't know where to place and what to put in. Please advice!

Thanks in advance!

**Comment by niwinz** [comment]
Hi!

Is just happens because you does not have a configuration module. For fix it, you should copy a app/coffee/config.coffee.example to app/coffee/config.coffee

**Comment by dArignac** [comment]
Yeah, great! Now it works, thanks!
