### ISSUE TITLE
Proposal for the header

### ISSUE THREAD

**Issue by guilhem-got** [kaleidos-ventures/taiga-front-old#25]
This version integrates the name of the project. This compensate a huge lack since its important to have the "where am I" information at glance. Important need if we consider multiproject profiles (eg designers)

As Greenmine is bound to be a "specialised public" application, at the end I think that no harm would be done reducing the "corporate" header to a simple logo. On top of that its location would be logical with the project/breadcrumb.

Thing change would serve the first objective and help to reduce the header space.

![header](https://f.cloud.github.com/assets/4123699/901623/59aa179a-fb83-11e2-9566-cc6bee307c63.gif)

**Comment by niwinz** [comment]
Hmm! Seems very nice! I go to experiment with this in few days! thanks!

**Comment by Xaviju** [comment]
Already redesigned header as wireframe suggests and added breadrumbs
