### ISSUE TITLE
Proposal for the task consulting/edition

### ISSUE THREAD

**Issue by guilhem-got** [kaleidos-ventures/taiga-front-old#26]
I still consider more consistent having a “one screen” data visualization with a switch between consulting and editing mode. I think we both gain clarity in data access and action affordance.

I used a modal window for the comment field to separate the modification and the explanation about it. On the other hand it helps to reduce the clutter produced by having a field that is not directly related to the task and hence would require an additional visual hierarchy. On top of that I have been told that comment was compulsory. Showing it as a step in the modification process would stress that fact and avoid error messages (in case the comment field is far from the edited field and not visible). 
A nice feature could be: in case of closing ("Close" button) the modal window to keep on editing the task, saving again the modifications would show once more the already entered text.

![taskdetailvis](https://f.cloud.github.com/assets/4123699/902052/91535eb4-fb8c-11e2-98b9-af75f483c953.gif)

![taskdetailedit](https://f.cloud.github.com/assets/4123699/902053/967f966e-fb8c-11e2-9eda-731d5076744b.gif)

![taskdetaileditcomment](https://f.cloud.github.com/assets/4123699/902054/9be3a028-fb8c-11e2-9006-fb625803c611.gif)

**Comment by niwinz** [comment]
Same as header! Good idea! The only thing that I don't like are comments on lightbox.  I will put it's on edit form as other field (as idea)!

Thanks!
